theme: jekyll-theme-minimal
title: ADA Template Website
description: A template website for ADA
show_downloads: True
navigation:
  - title: Projet-abrakadada
    url: /
  - title: Wikispeedia : A glimpse of the human brain
    url: example
