theme: jekyll-theme-minimal
title: Wikispeedia : A glimpse of the human brain
description: A template website for ADA, project-abrakadada
show_downloads: True
navigation:
  - title:
    url: /
  - title:
    url: example
